export const processType = {
    ASYNC_DELETE: 'ASYNC_DELETE',
    ASYNC_INSERT: 'ASYNC_INSERT',
    ASYNC_LOAD: 'ASYNC_LOAD',
    ASYNC_LOAD_ALL: 'ASYNC_LOAD_ALL',
    ASYNC_LOAD_ONE: 'ASYNC_LOAD_ONE',
    ASYNC_LOAD_QUERY: 'ASYNC_LOAD_QUERY',
    ASYNC_UPDATE: 'ASYNC_UPDATE',
    LOAD_ONE: 'LOAD_ONE',
    PROCESS_ENTRY_CONCERNS_ADDITION: 'PROCESS_ENTRY_CONCERNS_ADDITION',
    PROCESS_ENTRY_PROPERTY_CHANGE: 'PROCESS_ENTRY_PROPERTY_CHANGE',
    SET_DETAILING_OPTIONS: 'SET_DETAILING_OPTIONS',
    SET_DETAILS_PROCESS: 'SET_DETAILS_PROCESS',
    SET_ENTRY_DIALOG_OPTIONS: 'SET_ENTRY_DIALOG_OPTIONS',
    SET_HAS_DETAILS_PROCESS: 'SET_HAS_DETAILS_PROCESS'
};